model_params:
  name: 'WAE_MMD'
  input_shape: [128, 128, 1]
  latent_dim: 128
  regular_weight: 1000
  kernel_capacity: 0
  kernel_type: 'RBF'
  kernel_var: 2.0
  encoder_layers:
    - name: 'ResNet50v2'
      include_top: False
      weights: null
      input_shape: [128,128,1]
      pooling: 'max'
    - name: 'Dense'
      units: 512
      activation: 'relu'
    - name: 'Dense'
      units: 128

  decoder_layers:
    - name: 'Dense'
      units: 512
      activation: 'relu'
    - name: 'Dense'
      units: 2048
      activation: 'relu'
    - name: 'Reshape'
      target_shape: [1, 1, 2048]
    - name: 'UpSampling2D'
      size: 4

    - name: 'ResNet50v2_Decoder'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'    
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 1
      kernel_size: 3
      strides: [1,1]
      padding: 'same'

model_weight:
  path: 'save/wae_mmd_sate/WAE_MMDkernel_capacity0.h5'

multi_train_param:
  - - 'model_params'
    - 'kernel_capacity'
    - [0]

train_param:
  check_loss_cnt: 3
  epochs: 1000
  save_path: 'assets/wae_mmd_sate/cont/'
  save_model_path: 'save/wae_mmd_sate/cont/'
  save_iter: 5
  check_point_path: 'checkpoint/wae_mmd_sate/cont/'
  check_point_iter: 10
  log_dir: 'logs/wae_mmd_sate/cont/'

dataset_param:
  datatype: 'satellite'
  is_reverse: 'true'
  path: 'data/satellite'
  input_shape: [128, 128]
  color_mode: 'grayscale'
  test_split: 0.2
  batch_size: 64
  shuffle: True
  scale: 'sigmoid'
opt_param:
  name: 'Adam'
  LR: 0.0005