model_params:
  name: 'BetaTCVAE'
  input_shape: [64, 64, 3]
  latent_dim: 128
  alpha: 1.
  beta: 6.
  gamma: 1.
  train_data_size: 162080
  test_data_size: 40519
  loss_function_type: 'BCE'
  encoder_layers:
    - name: 'ResNet50v2'
      include_top: False
      weights: null
      input_shape: [64,64,3]
      pooling: 'max'

    - name: 'Dense'
      units: 1024
      activation: 'relu'
    - name: 'Dense'
      units: 256

  decoder_layers:
    - name: 'Dense'
      units: 512
      activation: 'relu'
    - name: 'Dense'
      units: 2048
      activation: 'relu'
    - name: 'Reshape'
      target_shape: [1, 1, 2048]
    - name: 'UpSampling2D'
      size: 4

    - name: 'ResNet50v2_Decoder'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'    
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 3
      kernel_size: 3
      strides: [1,1]
      padding: 'same'

train_param:
  check_loss_cnt: 5
  epochs: 1000
  save_path: 'assets/beta_tc_vae/'
  save_model_path: 'save/beta_tc_vae/'
  save_iter: 10
  check_point_path: 'checkpoint/beta_tc_vae/'
  check_point_iter: 100
  log_dir: 'logs/beta_tc_vae/'

dataset_param:
  datatype: 'celeba'
  path: 'data/celeba'
  input_shape: [64, 64]
  test_split: 0.2
  batch_size: 32
  shuffle: True
  scale: 'sigmoid'

opt_param:
  name: 'Adam'
  initial_learning_rate: 0.001
  decay_steps: 100
  decay_rate: 0.90