model_params:
  name: 'BetaVAE'
  input_shape: [128, 128, 1]
  latent_dim: 128
  beta: 1000
  kl_capacity_type: 'C'
  kl_capacity: 10
  encoder_layers:
    - name: 'Conv2D'
      filters: 32
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 64
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 128
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 256
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 512
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Flatten'
    - name: 'Dense'
      units: 256

  decoder_layers:
    - name: 'Dense'
      units: 8192
    - name: 'Reshape'
      target_shape: [4, 4, 512]

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 512
      strides: [2,2]
      padding: 'same'    
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 256
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 128
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 32
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 1
      kernel_size: 3
      strides: [1,1]
      padding: 'same'

train_param:
  check_loss_cnt: 3
  epochs: 300
  save_path: 'assets/beta_vae/'
  save_model_path: 'save/beta_vae/'
  save_iter: 5
  check_point_path: 'checkpoint/beta_vae/'
  check_point_iter: 5
  log_dir: 'logs/beta_vae/'

multi_train_param:
  - - 'model_params'
    - 'kl_capacity'
    - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

dataset_param:
  datatype: 'satellite'
  is_reverse: 'true'
  path: 'data/satellite'
  input_shape: [128, 128]
  color_mode: 'grayscale'
  test_split: 0.2
  batch_size: 64
  shuffle: True
  scale: 'sigmoid'

opt_param:
  name: 'Adam'
  LR: 0.0003