model_params:
  name: 'BetaTCVAE'
  input_shape: [64, 64, 3]
  latent_dim: 10
  anneal_steps: 10000
  alpha: 1.
  beta: 6.
  gamma: 1.
  train_data_size: 162080
  test_data_size: 40519
  loss_function_type: 'MSE'
  encoder_layers:
    - name: 'Conv2D'
      filters: 32
      kernel_size: 4
      strides: [2, 2]
      padding: 'same'
    - name : 'LeakyReLu'

    - name: 'Conv2D'
      filters: 32
      kernel_size: 4
      strides: [2, 2]
      padding: 'same'
    - name : 'LeakyReLu'

    - name: 'Conv2D'
      filters: 32
      kernel_size: 4
      strides: [2, 2]
      padding: 'same'
    - name : 'LeakyReLu'

    - name: 'Conv2D'
      filters: 32
      kernel_size: 4
      strides: [2, 2]
      padding: 'same'
    - name : 'LeakyReLu'
    
    - name: 'Flatten'

    - name: 'Dense'
      units: 256
      
    - name: 'Dense'
      units: 20

  decoder_layers:
    - name: 'Dense'
      units: 512
      
    - name: 'Reshape'
      target_shape: [4, 4, 32]

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 32
      strides: [2,2]
      padding: 'same'    
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 32
      strides: [2,2]
      padding: 'same'    
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 32
      strides: [2,2]
      padding: 'same'    
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 32
      strides: [2,2]
      padding: 'same'    
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 3
      kernel_size: 3
      strides: [1,1]
      padding: 'same'

train_param:
  check_loss_cnt: 6
  epochs: 50
  save_path: 'assets/beta_tc_vae/'
  save_model_path: 'save/beta_tc_vae/'
  save_iter: 10
  check_point_path: 'checkpoint/beta_tc_vae/'
  check_point_iter: 100
  log_dir: 'logs/beta_tc_vae/'

dataset_param:
  datatype: 'celeba'
  path: 'data/celeba'
  color_mode : 'rgb'
  input_shape: [64, 64]
  test_split: 0.2
  batch_size: 128
  shuffle: True
  scale: 'tanh'

opt_param:
  name: 'Adam'
  initial_learning_rate: 0.001
  decay_steps: 10000
  decay_rate: 0.99