model_params:
  name: 'VanillaVAE'
  input_shape: [128, 128, 1]
  latent_dim: 16
  loss_function_type: 'BCE'
  encoder_layers:
    - name: 'Conv2D'
      filters: 32
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 64
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 128
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 256
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 512
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'
    - name: 'Flatten'
    - name: 'Dense'
      units: 32

  decoder_layers:
    - name: 'Dense'
      units: 8192
    - name: 'Reshape'
      target_shape: [4, 4, 512]
    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 512
      strides: [2,2]
      padding: 'same'    
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 256
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 128
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 32
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 1
      kernel_size: 3
      strides: [1,1]
      padding: 'same'
      activation: 'sigmoid'

train_param:
  check_loss_cnt: 3
  epochs: 500
  save_path: 'assets/satellite/'
  save_model_path: 'save/'
  save_iter: 50
  check_point_path: 'checkpoint/'
  check_point_iter: 100
  log_dir: 'logs/'

dataset_param:
  datatype: 'satellite'
  is_reverse: 'true'
  path: 'data/satellite/'
  input_shape: [128, 128]
  color_mode: 'grayscale'
  test_split: 0.2
  batch_size: 64
  shuffle: True
  scale: 'sigmoid'

  
opt_param:
  name: 'Adam'
  LR: 0.0001
