model_params:
  name: 'VQVAE'
  input_shape: [128, 128, 1]
  latent_dim: 128
  num_embeddings: 512
  beta: 0.25
  encoder_layers:
    - name: 'ResNet50v2'
      include_top: False
      weights: null
      input_shape: [128,128,1]
      pooling: null
      _slice_layer_num: 78
   
    
  decoder_layers:
    - name: 'make_ResNet50v2_Decoder_VQVAE'

    - name: 'Conv2D'
      kernel_size: 3
      filters: 64
      strides: [1,1]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'    
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'    
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      kernel_size: 3
      filters: 1
      strides: [1,1]
      padding: 'same'
    
      
train_param:
  check_loss_cnt: 4
  epochs: 1000
  save_path: 'assets/VQVAE_sate/'
  save_model_path: 'save/VQVAE_sate/'
  save_iter: 10
  check_point_path: 'checkpoint/VQVAE_sate/'
  check_point_iter: 10
  log_dir: 'logs/VQVAE_sate/'

dataset_param:
  datatype: 'satellite'
  is_reverse: 'true'
  path: 'data/satellite'
  input_shape: [128, 128]
  color_mode: 'grayscale'
  test_split: 0.2
  batch_size: 64
  shuffle: True
  scale: 'sigmoid'

opt_param:
  name: 'Adam'
  LR: 0.001