model_params:
  name: 'WAE_GAN'
  input_shape: [128, 128, 3]
  latent_dim: 128
  regular_weight: 10
  encoder_layers:
    - name: 'ResNet50v2'
      include_top: False
      weights: null
      input_shape: [128,128,3]
      pooling: 'max'
    - name: 'Dense'
      units: 512
      activation: 'relu'
    - name: 'Dense'
      units: 128
    
  latent_discriminator_layers: 
    - name: 'Dense'
      units: 1024
      activation: 'relu'
    - name: 'Dense'
      units: 1024
      activation: 'relu'
    - name: 'Dense'
      units: 1
      activation: 'sigmoid'

  decoder_layers:
    - name: 'Dense'
      units: 512
      activation: 'relu'
    - name: 'Dense'
      units: 2048
      activation: 'relu'
    - name: 'Reshape'
      target_shape: [1, 1, 2048]
    - name: 'UpSampling2D'
      size: 4

    - name: 'ResNet50v2_Decoder'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'    
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 3
      kernel_size: 3
      strides: [1,1]
      padding: 'same'


train_param:
  check_loss_cnt: 3
  epochs: 1000
  save_path: 'assets/wae_gan_sate_Res50/'
  save_model_path: 'save/wae_gan_sate_Res50/'
  save_iter: 10
  check_point_path: 'checkpoint/wae_gan_sate_Res50/'
  check_point_iter: 100
  log_dir: 'logs/wae_gan_sate_Res50/'

dataset_param:
  datatype: 'satellite'
  path: 'data/satellite/rgb'
  input_shape: [128, 128]
  color_mode: 'rgb'
  test_split: 0.2
  batch_size: 32
  shuffle: True
  scale: 'sigmoid'

opt_param:
  name: 'Adam'
  LR: 0.0001