model_params:
  name: 'WAE_MMD'
  input_shape: [128, 128, 3]
  latent_dim: 128
  regular_weight: 1000
  kernel_capacity: 0
  kernel_type: 'RBF'
  kernel_var: 2.0
  loss_function_type: 'BCE'
  encoder_layers:
    - name: 'ResNet50v2'
      include_top: False
      weights: null
      input_shape: [128,128,3]
      pooling: 'max'
    - name: 'Dense'
      units: 512
      activation: 'relu'
    - name: 'Dense'
      units: 128

  decoder_layers:
    - name: 'Dense'
      units: 512
      activation: 'relu'
    - name: 'Dense'
      units: 2048
      activation: 'relu'
    - name: 'Reshape'
      target_shape: [1, 1, 2048]
    - name: 'UpSampling2D'
      size: 4

    - name: 'ResNet50v2_Decoder'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'    
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 3
      kernel_size: 3
      strides: [1,1]
      padding: 'same'

multi_train_param:
  - - 'model_params'
    - 'kernel_capacity'
    - [0,]

train_param:
  check_loss_cnt: 3
  epochs: 1000
  save_path: 'assets/wae_mmd_sate/'
  save_model_path: 'save/wae_mmd_sate/'
  save_iter: 10
  check_point_path: 'checkpoint/wae_mmd_sate/'
  check_point_iter: 100
  log_dir: 'logs/wae_mmd_sate/'

dataset_param:
  datatype: 'satellite'
  path: 'data/satellite/rgb'
  input_shape: [128, 128]
  color_mode: 'rgb'
  test_split: 0.2
  batch_size: 32
  shuffle: True
  scale: 'sigmoid'

opt_param:
  name: 'Adam'
  initial_learning_rate: 0.001
  decay_steps: 200
  decay_rate: 0.95