model_params:
  name: 'WAE_MMD'
  input_shape: [128, 128, 3]
  latent_dim: 128
  regular_weight: 100
  kernel_type: 'RBF'
  kernel_var: 2.0
  encoder_layers:
    - name: 'Conv2D'
      filters: 32
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 64
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 128
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 256
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 512
      kernel_size: 3
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Flatten'
    - name: 'Dense'
      units: 128

  decoder_layers:
    - name: 'Dense'
      units: 8192
    - name: 'Reshape'
      target_shape: [4, 4, 512]

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 512
      strides: [2,2]
      padding: 'same'    
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 256
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 128
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 64
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2DTranspose'
      kernel_size: 3
      filters: 32
      strides: [2,2]
      padding: 'same'
    - name: 'BN'
    - name: 'LeakyReLu'

    - name: 'Conv2D'
      filters: 3
      kernel_size: 3
      strides: [1,1]
      padding: 'same'

train_param:
  check_loss_cnt: 3
  epochs: 100
  save_path: 'assets/wae_mmd/'
  save_model_path: 'save/wae_mmd/'
  save_iter: 5
  check_point_path: 'checkpoint/wae_mmd/'
  check_point_iter: 5
  log_dir: 'logs/wae_mmd/'

dataset_param:
  path: 'data/celeba'
  input_shape: [128, 128]
  test_split: 0.2
  batch_size: 32
  shuffle: True
  scale: 'sigmoid'

opt_param:
  name: 'Adam'
  LR: 0.0001