hp_params:
  loss_function: ['MSE', 'BCE']
  learning_rate: [0.001, 0.0005, 0.0001]
  network_type: ['deep', 'shallow']
  latent_dim: [32, 64, 128]

model_params_shallow:
  _32:
    name: 'VanillaVAE'
    input_shape: [128, 128, 1]
    latent_dim: 32
    encoder_layers:
      - name: 'Conv2D'
        filters: 32
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 64
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 128
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 256
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 512
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Flatten'
      - name: 'Dense'
        units: 64

    decoder_layers:
      - name: 'Dense'
        units: 8192
      - name: 'Reshape'
        target_shape: [4, 4, 512]
      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 512
        strides: [2,2]
        padding: 'same'    
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 256
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 128
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 64
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 32
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 1
        kernel_size: 3
        strides: [1,1]
        padding: 'same'

  _64:
    name: 'VanillaVAE'
    input_shape: [128, 128, 1]
    latent_dim: 64
    encoder_layers:
      - name: 'Conv2D'
        filters: 32
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 64
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 128
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 256
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 512
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Flatten'
      - name: 'Dense'
        units: 128

    decoder_layers:
      - name: 'Dense'
        units: 8192
      - name: 'Reshape'
        target_shape: [4, 4, 512]
      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 512
        strides: [2,2]
        padding: 'same'    
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 256
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 128
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 64
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 32
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 1
        kernel_size: 3
        strides: [1,1]
        padding: 'same'

  _128:
    name: 'VanillaVAE'
    input_shape: [128, 128, 1]
    latent_dim: 128
    encoder_layers:
      - name: 'Conv2D'
        filters: 32
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 64
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 128
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 256
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 512
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Flatten'
      - name: 'Dense'
        units: 256

    decoder_layers:
        - name: 'Dense'
          units: 8192
        - name: 'Reshape'
          target_shape: [4, 4, 512]
        - name: 'Conv2DTranspose'
          kernel_size: 3
          filters: 512
          strides: [2,2]
          padding: 'same'    
        - name: 'BN'
        - name: 'LeakyReLu'

        - name: 'Conv2DTranspose'
          kernel_size: 3
          filters: 256
          strides: [2,2]
          padding: 'same'
        - name: 'BN'
        - name: 'LeakyReLu'

        - name: 'Conv2DTranspose'
          kernel_size: 3
          filters: 128
          strides: [2,2]
          padding: 'same'
        - name: 'BN'
        - name: 'LeakyReLu'

        - name: 'Conv2DTranspose'
          kernel_size: 3
          filters: 64
          strides: [2,2]
          padding: 'same'
        - name: 'BN'
        - name: 'LeakyReLu'

        - name: 'Conv2DTranspose'
          kernel_size: 3
          filters: 32
          strides: [2,2]
          padding: 'same'
        - name: 'BN'
        - name: 'LeakyReLu'

        - name: 'Conv2D'
          filters: 1
          kernel_size: 3
          strides: [1,1]
          padding: 'same'


model_params_deep:
  _32:
    name: 'VanillaVAE'
    input_shape: [128, 128, 1]
    latent_dim: 32
    encoder_layers:
      - name: 'ResNet50v2'
        include_top: False
        weights: null
        input_shape: [128,128,1]
        pooling: 'max'
      - name: 'Dense'
        units: 512
        activation: 'relu'
      - name: 'Dense'
        units: 64

    decoder_layers:
      - name: 'Dense'
        units: 512
        activation: 'relu'
      - name: 'Dense'
        units: 2048
        activation: 'relu'
      - name: 'Reshape'
        target_shape: [1, 1, 2048]
      - name: 'UpSampling2D'
        size: 4

      - name: 'ResNet50v2_Decoder'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 64
        strides: [2,2]
        padding: 'same'    
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 64
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 1
        kernel_size: 3
        strides: [1,1]
        padding: 'same'

  _64:
    name: 'VanillaVAE'
    input_shape: [128, 128, 1]
    latent_dim: 64
    encoder_layers:
      - name: 'ResNet50v2'
        include_top: False
        weights: null
        input_shape: [128,128,1]
        pooling: 'max'
      - name: 'Dense'
        units: 512
        activation: 'relu'
      - name: 'Dense'
        units: 128

    decoder_layers:
      - name: 'Dense'
        units: 512
        activation: 'relu'
      - name: 'Dense'
        units: 2048
        activation: 'relu'
      - name: 'Reshape'
        target_shape: [1, 1, 2048]
      - name: 'UpSampling2D'
        size: 4

      - name: 'ResNet50v2_Decoder'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 64
        strides: [2,2]
        padding: 'same'    
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 64
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 1
        kernel_size: 3
        strides: [1,1]
        padding: 'same'

  _128:
    name: 'VanillaVAE'
    input_shape: [128, 128, 1]
    latent_dim: 128
    encoder_layers:
      - name: 'ResNet50v2'
        include_top: False
        weights: null
        input_shape: [128,128,1]
        pooling: 'max'
      - name: 'Dense'
        units: 512
        activation: 'relu'
      - name: 'Dense'
        units: 256

    decoder_layers:
        - name: 'Dense'
          units: 512
          activation: 'relu'
        - name: 'Dense'
          units: 2048
          activation: 'relu'
        - name: 'Reshape'
          target_shape: [1, 1, 2048]
        - name: 'UpSampling2D'
          size: 4

        - name: 'ResNet50v2_Decoder'

        - name: 'Conv2DTranspose'
          kernel_size: 3
          filters: 64
          strides: [2,2]
          padding: 'same'    
        - name: 'BN'
        - name: 'LeakyReLu'

        - name: 'Conv2DTranspose'
          kernel_size: 3
          filters: 64
          strides: [2,2]
          padding: 'same'
        - name: 'BN'
        - name: 'LeakyReLu'

        - name: 'Conv2D'
          filters: 1
          kernel_size: 3
          strides: [1,1]
          padding: 'same'



train_param:
  check_loss_cnt: 3
  epochs: 1000
  save_path: 'assets/vanila_vae_thesis/'
  save_model_path: 'save/vanila_vae_thesis/'
  save_iter: 100
  check_point_path: 'checkpoint/vanila_vae_thesis/'
  check_point_iter: 100
  log_dir: 'logs/vanila_vae_thesis/'

dataset_param:
  path: 'data/satellite'
  is_reverse: 'true'
  datatype: 'satellite'
  input_shape: [128, 128]
  color_mode: 'grayscale'
  test_split: 0.2
  batch_size: 32
  shuffle: True
  scale: 'sigmoid'

opt_param:
  name: 'Adam'
  LR: 0.0001